#pragma once

// Monster Attack
#define NORMAL_MONSTER_ATTACK 20
#define MEDIUM_MONSTER_ATTACK 30
#define HARD_MONSTER_ATTACK 40
#define BOSS_MONSTER_ATTACK 500

// Monster Armor
#define NORMAL_MONSTER_ARMOR 10
#define MEDIUM_MONSTER_ARMOR 30
#define HARD_MONSTER_ARMOR 50
#define BOSS_MONSTER_ARMOR 100

// Monster HP
#define NORMAL_MONSTER_HP_MAX 200
#define MEDIUM_MONSTER_HP_MAX 300
#define HARD_MONSTER_HP_MAX 400
#define BOSS_MONSTER_HP_MAX 5000

// Monster MP
#define NORMAL_MONSTER_MP_MAX 200.f
#define MEDIUM_MONSTER_MP_MAX 300.f
#define HARD_MONSTER_MP_MAX 400.f
#define BOSS_MONSTER_MP_MAX 5000.f

// Monster MP
#define NORMAL_MONSTER_DISTANCE 500.f
#define MEDIUM_MONSTER_DISTANCE 700.f
#define HARD_MONSTER_DISTANCE 900.f
#define BOSS_MONSTER_DISTANCE 2000.f
