#pragma once

#define EFFECT_HIT_PROTO					  "HitEffectProto"
#define EFFECT_BULLETSTART_PROTO			  "BulletStartEffectProto"
#define EFFECT_SURPRISE_PROTO				  "SurpriseEffectProto"
#define EFFECT_CASING_PROTO					  "CasingEffectProto"
#define EFFECT_DASH_PROTO					  "DashEffectProto"
#define TELEPORT_MOUSE_PROTO				  "TeleportMouseProto"
#define MONSTER_DUCK1_PROTO					  "MonsterProto"
#define PLAYER_BULLET_PROTO					  "PlayerBulletProto"
#define POTION_HP_PROTO						  "HPPotionProto"
#define POTION_MP_PROTO						  "MPPotionProto"
#define MONSTER_BULLET_PROTO                  "MonsterBulletProto"
#define PLAYER_SKILL_SLOWMOTION_BULLET_PROTO  "SkillSlowMotionAttackBulletProto"

#define GUN_PISTOL_LIGHT_PROTO     "PistolLightProto"
#define GUN_PISTOL_MEDIUM_PROTO    "PistolMediumProto"
#define GUN_PISTOL_HEAVY_PROTO     "PistolHeavyProto"
#define GUN_SHOTGUN_LIGHT_PROTO    "ShotGunLightProto"
#define GUN_SHOTGUN_MEDIUM_PROTO   "ShotGunMediumProto"
#define GUN_SHOTGUN_HEAVY_PROTO    "ShotGunHeavyProto"
